/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlsinhvien;


import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author An
 */
public class frmDiem extends javax.swing.JFrame {

    /**
     * Creates new form frmDiem
     */
    public frmDiem() {
        initComponents();
    }
    
    public String Mssv;
    public String getMssv() {
        return Mssv;
    }
    public void setMssv(String mssv) {
        this.Mssv=mssv;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKetQua = new javax.swing.JTable();
        jblNamHoc = new javax.swing.JLabel();
        cboNamHoc = new javax.swing.JComboBox();
        jblHocKy = new javax.swing.JLabel();
        cboHocKy = new javax.swing.JComboBox();
        btnLietKe = new javax.swing.JButton();
        jblTinChiDK = new javax.swing.JLabel();
        txtTinChiDK = new javax.swing.JTextField();
        jblDiemTB = new javax.swing.JLabel();
        txtDiemTB = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jblTL = new javax.swing.JLabel();
        txtTL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KẾT QUẢ HỌC TẬP");

        tbKetQua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã học phần", "Tên học phần", "Nhóm", "Tín chỉ", "Điểm chữ", "Điểm số"
            }
        ));
        jScrollPane1.setViewportView(tbKetQua);

        jblNamHoc.setText("Năm học");

        jblHocKy.setText("Học kỳ");

        btnLietKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Listed.png"))); // NOI18N
        btnLietKe.setText("Liệt kê");
        btnLietKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLietKeActionPerformed(evt);
            }
        });

        jblTinChiDK.setText("Tổng số tín chỉ đăng kí");

        jblDiemTB.setText("Điểm trung bình học kì");

        txtDiemTB.setPreferredSize(new java.awt.Dimension(90, 26));

        btnQuayLai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Back.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Printer.png"))); // NOI18N
        btnIn.setText("In bảng điểm");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jblTL.setText("Tổng số tín chỉ tích lũy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jblNamHoc)
                        .addGap(32, 32, 32)
                        .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jblHocKy)
                        .addGap(36, 36, 36)
                        .addComponent(cboHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(157, 157, 157)))
                .addComponent(btnLietKe)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnQuayLai)
                        .addGap(115, 115, 115)
                        .addComponent(btnIn)
                        .addGap(117, 117, 117)
                        .addComponent(btnThoat)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jblTL)
                            .addComponent(jblTinChiDK))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTL, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtTinChiDK))
                        .addGap(141, 141, 141)
                        .addComponent(jblDiemTB)
                        .addGap(35, 35, 35)
                        .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblNamHoc)
                            .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblHocKy)
                            .addComponent(cboHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnLietKe)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblTinChiDK)
                    .addComponent(txtTinChiDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblDiemTB)
                    .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblTL)
                    .addComponent(txtTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQuayLai)
                        .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int output = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if(output == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            enableField(false);
            clsData.OpenConnect();
            PreparedStatement stm = clsData.con.prepareStatement("Select distinct NamHoc\n" +
                                                                    "from GiangDay G join DiemMH D on G.Nhom=D.Nhom\n" +
                                                                    "where D.MSSV=?");
            stm.setString(1, Mssv);
            ResultSet rs = stm.executeQuery();
            while(rs.next()) {
                cboNamHoc.addItem(rs.getString(1));
            }
            cboNamHoc.addItem("Tất cả");
            
            PreparedStatement stm1 = clsData.con.prepareStatement("Select distinct HocKy\n" +
                                                                    "from GiangDay G join DiemMH D on G.Nhom=D.Nhom\n" +
                                                                    "where D.MSSV=?");
            stm1.setString(1, Mssv);
            ResultSet rs1 = stm1.executeQuery();
            while(rs1.next()) {
                cboHocKy.addItem(rs1.getString(1));
            }
            cboHocKy.addItem("Tất cả");
            clsData.CloseConnect();
        } catch (SQLException ex) {
            Logger.getLogger(frmDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    public void enableField(Boolean stt) {
        jblTinChiDK.setVisible(stt);
        txtTinChiDK.setVisible(stt);
        jblDiemTB.setVisible(stt);
        txtDiemTB.setVisible(stt);
        jblTL.setVisible(stt);
        txtTL.setVisible(stt);
    }
      
    public Float DiemTBHK = 0.0f;
    private void btnLietKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLietKeActionPerformed
        try {
            // TODO add your handling code here:
            clsData.OpenConnect();
            PreparedStatement stm;
            int tinChiDK = 0;
            int TL = 0;
            float diemTB = 0;
            float diem = 0;
            //Năm học và học kỳ là tất cả
            if(cboNamHoc.getSelectedItem().equals("Tất cả") && cboHocKy.getSelectedItem().equals("Tất cả")) {
                stm = clsData.con.prepareStatement("Select M.MaMon, M.TenMon, G.Nhom, M.TinChi, D.DiemChu, D.DiemSo\n" +
                                                    "from GiangDay G join MonHoc M on G.MaMon=M.MaMon \n" +
                                                    "join DiemMH D on G.Nhom=D.Nhom\n" +
                                                    "where D.MSSV=?");
                stm.setString(1, Mssv);
            }
            //Năm học bất kì và học kỳ là tất cả
            else if (cboHocKy.getSelectedItem().equals("Tất cả")) {
                stm = clsData.con.prepareStatement("Select M.MaMon, M.TenMon, G.Nhom, M.TinChi, D.DiemChu, D.DiemSo\n" +
                                                    "from GiangDay G join MonHoc M on G.MaMon=M.MaMon \n" +
                                                    "join DiemMH D on G.Nhom=D.Nhom\n" +
                                                    "where G.NamHoc=? and D.MSSV=?");
                stm.setString(1, cboNamHoc.getSelectedItem().toString());
                stm.setString(2, Mssv);
            }
            //Năm học và học kỳ là bất kì
            else {
                stm = clsData.con.prepareStatement("Select distinct M.MaMon, M.TenMon, G.Nhom, M.TinChi, D.DiemChu, D.DiemSo\n" +
                                                    "from GiangDay G join MonHoc M on G.MaMon=M.MaMon \n" +
                                                    "join DiemMH D on G.Nhom=D.Nhom\n" +
                                                    "where G.NamHoc=? and D.MSSV=? and G.HocKy=?");
                stm.setString(1, cboNamHoc.getSelectedItem().toString());
                stm.setString(2, Mssv);
                stm.setString(3, cboHocKy.getSelectedItem().toString());
            }
            
            ResultSet rs = stm.executeQuery();
            DefaultTableModel m = new DefaultTableModel(new Object[]{"STT", "Mã Học Phần","Tên Học Phần", "Nhóm", "Tín chỉ", "Điểm Chữ", "Điểm Số"},0);
            tbKetQua.setModel(m);
            //Set cho cột tên học phần rộng hơn 
            for(int i=0; i < tbKetQua.getColumnCount(); i++) {
//                if(i==0 || i==1)
//                   tbKetQua.getColumnModel().getColumn(i).setPreferredWidth(70);
                if(i==2)
                    tbKetQua.getColumnModel().getColumn(i).setPreferredWidth(300);
            }
            
            int stt=0;
            while(rs.next()) {
                stt++;
                ((DefaultTableModel)tbKetQua.getModel()).addRow(new Object[]{stt, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getFloat(6)});
                
                if(rs.getString(5).equals("A")) {
                    diem = 4;
                } else if(rs.getString(5).equals("B+")) {
                    diem = 3.5f;
                } else if(rs.getString(5).equals("B")) {
                    diem = 3;
                } else if(rs.getString(5).equals("C+")) {
                    diem = 2.5f;
                } else if(rs.getString(5).equals("C")) {
                    diem = 2;
                } else if(rs.getString(5).equals("D+")) {
                    diem = 1.5f;
                } else if(rs.getString(5).equals("D")) {
                    diem = 1;
                }
                
                //Nếu chưa nhập điểm hoặc bị điểm F thì sẽ không tính tích lũy
                if(!rs.getString(5).equals("") && !rs.getString(5).equals("F") ) {
                    TL += rs.getInt(4);
                    diemTB += diem * rs.getInt(4);
                }
                tinChiDK += rs.getInt(4);
            }
            
            enableField(true);
            txtTL.setText(String.valueOf(TL));
            DiemTBHK = diemTB / TL;
            txtTinChiDK.setText(String.valueOf(tinChiDK));
            
            DecimalFormat df = new DecimalFormat("0.00");
            if(!String.valueOf(DiemTBHK).equals("NaN")) {
                //txtDiemTB.setText(String.valueOf(DiemTBHK));
                txtDiemTB.setText(String.valueOf(df.format(DiemTBHK)));
            } else {
                txtDiemTB.setText("0.00");
            }
     
            clsData.CloseConnect();
        } catch (SQLException ex) {
            Logger.getLogger(frmDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLietKeActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        try {
            TableModel m = tbKetQua.getModel();
            JFileChooser dFile = new JFileChooser();
            dFile.showSaveDialog(null);
            String str = dFile.getSelectedFile().toString() + ".txt";
            //System.out.println(str);
            File file = new File(str);
            //File file = new File("D:\\Java1\\file6.txt");
            if (file.createNewFile()){
                FileWriter writer = new FileWriter(file);
                writer.write("MSSV: "+Mssv+"\n");
                writer.write("Họ và tên: "+this.getTitle()+"\n");
                writer.write("\n\n\t\t\t\tBẢNG ĐIỂM HỌC TẬP\n\n");
                for( int i=0; i < m.getRowCount(); i++) {
                    for(int j=0; j < m.getColumnCount();j++) {
                        writer.write(m.getValueAt(i, j).toString()+ "\t");
                    }
                    writer.write("\n");
                }
                writer.write("\nTổng số tín chỉ đã đăng ký: "+txtTinChiDK.getText()+"\n");
                writer.write("Tổng số tín chỉ đã hoàn thành: "+txtTL.getText()+"\n");
                writer.write("Điểm trung bình: "+txtDiemTB.getText()+"\n");
                writer.close();
                JOptionPane.showMessageDialog(this, "Lưu file thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "File này đã tồn tại!","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(frmDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLietKe;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox cboHocKy;
    private javax.swing.JComboBox cboNamHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblDiemTB;
    private javax.swing.JLabel jblHocKy;
    private javax.swing.JLabel jblNamHoc;
    private javax.swing.JLabel jblTL;
    private javax.swing.JLabel jblTinChiDK;
    private javax.swing.JTable tbKetQua;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtTL;
    private javax.swing.JTextField txtTinChiDK;
    // End of variables declaration//GEN-END:variables
}
