/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlsinhvien;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author An
 */
public class frmMainGV extends javax.swing.JFrame {

    /**
     * Creates new form frmMainGV
     */
    public frmMainGV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLop = new javax.swing.JTable();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnThemSV = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboNamHoc = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboHocKy = new javax.swing.JComboBox();
        btnLietKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("THÔNG TIN CÁC LỚP HỌC");

        tbLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã môn", "Tên môn", "Nhóm"
            }
        ));
        jScrollPane1.setViewportView(tbLop);

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Update.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật điểm");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThemSV.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThemSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThemSV.setText("Thêm sinh viên");
        btnThemSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSVActionPerformed(evt);
            }
        });

        jLabel2.setText("Năm học");

        jLabel3.setText("Học kỳ");

        btnLietKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Listed.png"))); // NOI18N
        btnLietKe.setText("Liệt kê");
        btnLietKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLietKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnThemSV)
                        .addGap(72, 72, 72)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(cboHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnLietKe)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLietKe))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThemSV))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String TenMon;
    public String Nhom;
    public String maMon;
    public String maGV;

    public String getMaGV() {
        return maGV;
    }

    public void setMaGV(String MaGV) {
        this.maGV = MaGV;
    }
    
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int output = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (output == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            clsData.OpenConnect();
            PreparedStatement stm = clsData.con.prepareStatement("Select distinct NamHoc from GiangDay where MaGV=?");
            stm.setString(1, maGV);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                cboNamHoc.addItem(rs.getString(1));
            }

            PreparedStatement stm1 = clsData.con.prepareStatement("Select distinct HocKy from GiangDay where MaGV=?");
            stm1.setString(1, maGV);
            ResultSet rs1 = stm1.executeQuery();
            while (rs1.next()) {
                cboHocKy.addItem(rs1.getString(1));
            }
            clsData.CloseConnect();
        } catch (SQLException ex) {
            Logger.getLogger(frmMainGV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        frmCapNhatDiem CN = new frmCapNhatDiem();
        int index = tbLop.getSelectedRow();
        TableModel m = tbLop.getModel();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhóm môn học muốn cập nhật điểm!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            maMon = m.getValueAt(index, 1).toString();
            TenMon = m.getValueAt(index, 2).toString();
            Nhom = m.getValueAt(index, 3).toString();

            CN.setVisible(true);
            CN.setMaGV(maGV);
            CN.setTenNhom(Nhom);
            CN.setMaMon(maMon);
            CN.setTitle("Môn: " + TenMon + " - Nhóm: " + Nhom);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThemSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSVActionPerformed
        // TODO add your handling code here:
        frmThongTin t = new frmThongTin();
        t.setVisible(true);
        t.setTitle("Thêm thông tin sinh viên");
        t.setMaGV(maGV);
        t.setNhom(Nhom);
        t.setMaMon(maMon);
    }//GEN-LAST:event_btnThemSVActionPerformed

    private void btnLietKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLietKeActionPerformed
        // TODO add your handling code here:
        try {
            clsData.OpenConnect();
            PreparedStatement stm = clsData.con.prepareStatement("Select distinct G.MaMon, M.TenMon, G.Nhom\n"
                                                                    + "from GiangDay G join MonHoc M on G.MaMon = M.MaMon\n"
                                                                    + "where G.MaGV=? and G.NamHoc=? and G.HocKy=?");
            stm.setString(1, maGV);
            stm.setString(2, cboNamHoc.getSelectedItem().toString());
            stm.setString(3, cboHocKy.getSelectedItem().toString());
            ResultSet rs = stm.executeQuery();
            DefaultTableModel m = new DefaultTableModel(new Object[]{"STT", "Mã Môn", "Tên Môn", "Nhóm"}, 0);
            tbLop.setModel(m);
            int stt = 0;
            while (rs.next()) {
                stt++;
                ((DefaultTableModel) tbLop.getModel()).addRow(new Object[]{stt, rs.getString(1), rs.getString(2), rs.getString(3)});
            }
            clsData.CloseConnect();
        } catch (SQLException ex) {
            Logger.getLogger(frmMainGV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLietKeActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainGV().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLietKe;
    private javax.swing.JButton btnThemSV;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox cboHocKy;
    private javax.swing.JComboBox cboNamHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLop;
    // End of variables declaration//GEN-END:variables
}
