/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlsinhvien;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author An
 */
public class frmThongTin extends javax.swing.JFrame {

    /**
     * Creates new form frmThongTin
     */
    public frmThongTin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnGioiTinh = new javax.swing.ButtonGroup();
        jblTitle = new javax.swing.JLabel();
        jblMa = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        jblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jblGioiTinh = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        jblLop = new javax.swing.JLabel();
        txtLop = new javax.swing.JTextField();
        jblNganhHoc = new javax.swing.JLabel();
        txtNganhHoc = new javax.swing.JTextField();
        jblKhoaHoc = new javax.swing.JLabel();
        txtKhoaHoc = new javax.swing.JTextField();
        jblKhoa = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        jblMK = new javax.swing.JLabel();
        txtMK = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jblTitle.setText("THÔNG TIN SINH VIÊN");

        jblMa.setText("Mã SV");

        txtMSSV.setForeground(new java.awt.Color(153, 153, 153));
        txtMSSV.setText("B1234567");
        txtMSSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMSSVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMSSVFocusLost(evt);
            }
        });
        txtMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMSSVActionPerformed(evt);
            }
        });

        jblHoTen.setText("Họ tên");

        jblNgaySinh.setText("Ngày sinh");

        txtNgaySinh.setForeground(new java.awt.Color(153, 153, 153));
        txtNgaySinh.setText("YYYY-MM-DD");
        txtNgaySinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNgaySinhFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNgaySinhFocusLost(evt);
            }
        });

        jblGioiTinh.setText("Giới tính");

        gbtnGioiTinh.add(radNam);
        radNam.setSelected(true);
        radNam.setText("Nam");

        gbtnGioiTinh.add(radNu);
        radNu.setText("Nữ");

        jblLop.setText("Lớp");

        jblNganhHoc.setText("Ngành học");

        jblKhoaHoc.setText("Khóa học");

        txtKhoaHoc.setForeground(new java.awt.Color(153, 153, 153));
        txtKhoaHoc.setText("44 (2018)");
        txtKhoaHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKhoaHocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKhoaHocFocusLost(evt);
            }
        });

        jblKhoa.setText("Khoa");

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jblMK.setText("Mật khẩu");

        txtMK.setToolTipText("");

        btnQuayLai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Back.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Update.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblMa)
                            .addComponent(jblHoTen)
                            .addComponent(jblNgaySinh)
                            .addComponent(jblGioiTinh)
                            .addComponent(jblLop)
                            .addComponent(jblNganhHoc)
                            .addComponent(jblKhoaHoc)
                            .addComponent(jblKhoa)
                            .addComponent(jblMK))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                            .addComponent(txtNganhHoc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMSSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(radNam)
                                .addGap(50, 50, 50)
                                .addComponent(radNu))
                            .addComponent(txtKhoaHoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTen)
                            .addComponent(txtMK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuayLai)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTitle)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblMa)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblHoTen)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNgaySinh)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblGioiTinh)
                    .addComponent(radNam)
                    .addComponent(radNu))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblLop)
                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNganhHoc)
                    .addComponent(txtNganhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblKhoaHoc)
                    .addComponent(txtKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblKhoa)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblMK)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuayLai))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String Nhom;

    public String getNhom() {
        return Nhom;
    }

    public void setNhom(String nhom) {
        this.Nhom = nhom;
    }

    public String maGV;

    public String getMaGV() {
        return maGV;
    }

    public void setMaGV(String MaGV) {
        this.maGV = MaGV;
    }

    public String maMon;

    public String getMaMon() {
        return maMon;
    }

    public void setMaMon(String MaMon) {
        this.maMon = MaMon;
    }

    public void setBtnUp(boolean stt) {
        txtMSSV.enable(stt);
        jblMK.setVisible(stt);
        txtMK.setVisible(stt);
        btnLuu.setVisible(stt);
    }

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    public String mssv;
    public String hoTen;
    public String ngaySinh;
    public String GioiTinh;
    public String Lop;
    public String NganhHoc;
    public String KhoaHoc;
    public String Khoa;

    public void loadTT(String Mssv) {
        try {
            clsData.OpenConnect();
            PreparedStatement stm = clsData.con.prepareStatement("Select * from SinhVien where MSSV=?");
            stm.setString(1, Mssv);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                txtMSSV.setText(rs.getString(1));
                mssv = rs.getString(1);
                txtHoTen.setText(rs.getString(2));
                txtNgaySinh.setText(rs.getDate(3).toString());
                if (rs.getByte(4) == 1) {
                    radNam.setSelected(true);
                } else {
                    radNu.setSelected(true);
                }
                txtLop.setText(rs.getString(5));
                txtNganhHoc.setText(rs.getString(6));
                txtKhoaHoc.setText(rs.getString(7));
                txtKhoa.setText(rs.getString(8));
            }
            clsData.CloseConnect();
        } catch (SQLException ex) {
            Logger.getLogger(frmMainSV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Boolean CheckMSSV(String mssv) {
        if (mssv.matches("[A-Z][0-9]{7}")) {
            try {
                clsData.OpenConnect();
                PreparedStatement stl = clsData.con.prepareStatement("Select * from SinhVien where MSSV=?");
                stl.setString(1, mssv);
                ResultSet rs = stl.executeQuery();
                if (rs.next()) {
                    return false;
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmThongTin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return true;
    }

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        try {
            clsData.OpenConnect();
            PreparedStatement stm = clsData.con.prepareStatement("Insert into SinhVien values(?,?,?,?,?,?,?,?,?)");
            if(CheckMSSV(txtMSSV.getText())) {
                stm.setString(1, txtMSSV.getText());
                stm.setString(2, txtHoTen.getText());
                stm.setString(3, txtNgaySinh.getText());
                if (radNam.isSelected()) {
                    stm.setString(4, "1");
                } else {
                    stm.setString(4, "0");
                }
                stm.setString(5, txtLop.getText());
                stm.setString(6, txtNganhHoc.getText());
                stm.setString(7, txtKhoaHoc.getText());
                stm.setString(8, txtKhoa.getText());
                stm.setString(9, txtMK.getText());
                stm.executeUpdate();

                JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clsData.CloseConnect();
            } else {
                JOptionPane.showMessageDialog(this, "Sinh viên này đã tồn tại\n hoặc thông tin vừa nhập còn thiếu.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmThongTin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        try {
            // TODO add your handling code here:
            clsData.OpenConnect();
            PreparedStatement stm = clsData.con.prepareStatement("Update SinhVien set HoTenSV=?, NgaySinh=?, GioiTinh=?, Lop=?,\n"
                    + "NganhHoc=?, KhoaHoc=?, Khoa=?\n"
                    + "where MSSV=?");
            stm.setString(1, txtHoTen.getText());
            stm.setString(2, txtNgaySinh.getText());
            stm.setBoolean(3, radNam.isSelected());
            stm.setString(4, txtLop.getText());
            stm.setString(5, txtNganhHoc.getText());
            stm.setString(6, txtKhoaHoc.getText());
            stm.setString(7, txtKhoa.getText());
            stm.setString(8, mssv);
            stm.executeUpdate();

            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            clsData.CloseConnect();
            this.hide();
        } catch (SQLException ex) {
            Logger.getLogger(frmThongTin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtNgaySinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgaySinhFocusLost
        // TODO add your handling code here:
        if(txtNgaySinh.getText().equals("")) {
            txtNgaySinh.setText("YYYY-MM-DD");
            txtNgaySinh.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNgaySinhFocusLost

    private void txtNgaySinhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgaySinhFocusGained
        // TODO add your handling code here:
        if(txtNgaySinh.getText().equals("YYYY-MM-DD")) {
            txtNgaySinh.setText("");
            txtNgaySinh.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNgaySinhFocusGained

    private void txtMSSVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMSSVFocusLost
        // TODO add your handling code here:
        if(txtMSSV.getText().equals("")) {
            txtMSSV.setText("B1234567");
            txtMSSV.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtMSSVFocusLost

    private void txtMSSVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMSSVFocusGained
        // TODO add your handling code here:
        if(txtMSSV.getText().equals("B1234567")) {
            txtMSSV.setText("");
            txtMSSV.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtMSSVFocusGained

    private void txtKhoaHocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKhoaHocFocusLost
        // TODO add your handling code here:
        if(txtKhoaHoc.getText().equals("")) {
            txtKhoaHoc.setText("44 (2018)");
            txtKhoaHoc.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtKhoaHocFocusLost

    private void txtKhoaHocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKhoaHocFocusGained
        // TODO add your handling code here:
        if(txtKhoaHoc.getText().equals("44 (2018)")) {
            txtKhoaHoc.setText("");
            txtKhoaHoc.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtKhoaHocFocusGained

    private void txtMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMSSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThongTin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.ButtonGroup gbtnGioiTinh;
    private javax.swing.JLabel jblGioiTinh;
    private javax.swing.JLabel jblHoTen;
    private javax.swing.JLabel jblKhoa;
    private javax.swing.JLabel jblKhoaHoc;
    private javax.swing.JLabel jblLop;
    private javax.swing.JLabel jblMK;
    private javax.swing.JLabel jblMa;
    private javax.swing.JLabel jblNganhHoc;
    private javax.swing.JLabel jblNgaySinh;
    private javax.swing.JLabel jblTitle;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtKhoaHoc;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtNganhHoc;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
